"""TypeSafe Jev — optional fast computer-use policy.

Configuration, AX snapshots, grounded actions/gates, TypeSafe client, shadow
evaluation, and the active one-action fast loop (:mod:`jev.loop`). Completion
always returns to the existing vision agent for verification.
"""

from __future__ import annotations

from jev.actions import (
    OP_CLICK,
    OP_DONE,
    OP_ENTER,
    OP_ESCALATE,
    OP_ESCAPE,
    OP_FOCUS,
    OP_SCROLL_DOWN,
    OP_SCROLL_UP,
    OP_TAB,
    OP_TYPE,
    OP_WAIT,
    ExecutionPlan,
    action_requires_confirmation,
    candidates_by_id,
    classify_jev_input_privacy,
    dedupe_elements,
    enumerate_grounded_actions,
    evaluate_decision_gate,
    execute_grounded_action,
    extract_task_text,
    plan_execution,
    prune_candidates_for_choice,
    resolve_safe_scroll_point,
    validate_grounded_action,
)
from jev.client import (
    JevClient,
    JevClientStats,
    JevRequestState,
    ask_jev,
    build_choice_criteria,
    build_jev_state,
    parse_system_one_decision,
    typesafe_sdk_available,
)
from jev.choose import (
    advisory_candidates_from_options,
    inject_pseudo_options,
    normalize_agent_options,
    run_jev_choose,
    run_jev_choose_tool,
)
from jev.config import (
    JEV_CHOICE_MAX_OPTIONS,
    JEV_ENV_KEYS,
    JEV_MAX_CANDIDATES_HARD_CEILING,
    JevConfig,
    api_key_status,
    jev_choose_tool_enabled,
    load_jev_config,
)
from jev.text_candidates import (
    arithmetic_facts,
    extract_text_candidates,
    goal_names_destructive,
)
from jev.diagnostics import (
    JevSessionStats,
    StepTimer,
    record_jev_session_summary,
    scrub_for_logs,
)
from jev.loop import (
    WaitOutcome,
    action_signature,
    format_jev_handoff_prompt,
    jev_fast_loop_enabled,
    run_jev_fast_loop,
    wait_for_revision_change,
)
from jev.models import (
    ActionKind,
    DecisionGateResult,
    ElementFrame,
    GroundedAction,
    JevDecision,
    JevGateResult,
    JevGateVerdict,
    JevLoopResult,
    JevLoopStatus,
    PrivacyGateResult,
    TokenUsage,
    UIElement,
    UISnapshot,
    ValidationResult,
)
from jev.shadow import (
    ShadowEvaluationResult,
    record_jev_decision,
    run_shadow_evaluation,
    shadow_evaluation_enabled,
)

__all__ = [
    "JEV_CHOICE_MAX_OPTIONS",
    "JEV_ENV_KEYS",
    "JEV_MAX_CANDIDATES_HARD_CEILING",
    "ActionKind",
    "DecisionGateResult",
    "ElementFrame",
    "ExecutionPlan",
    "GroundedAction",
    "JevClient",
    "JevClientStats",
    "JevConfig",
    "JevDecision",
    "JevGateResult",
    "JevGateVerdict",
    "JevLoopResult",
    "JevLoopStatus",
    "JevRequestState",
    "JevSessionStats",
    "OP_CLICK",
    "OP_DONE",
    "OP_ENTER",
    "OP_ESCALATE",
    "OP_ESCAPE",
    "OP_FOCUS",
    "OP_SCROLL_DOWN",
    "OP_SCROLL_UP",
    "OP_TAB",
    "OP_TYPE",
    "OP_WAIT",
    "PrivacyGateResult",
    "ShadowEvaluationResult",
    "StepTimer",
    "TokenUsage",
    "UIElement",
    "UISnapshot",
    "ValidationResult",
    "WaitOutcome",
    "action_requires_confirmation",
    "action_signature",
    "advisory_candidates_from_options",
    "api_key_status",
    "arithmetic_facts",
    "ask_jev",
    "build_choice_criteria",
    "build_jev_state",
    "candidates_by_id",
    "classify_jev_input_privacy",
    "dedupe_elements",
    "enumerate_grounded_actions",
    "evaluate_decision_gate",
    "execute_grounded_action",
    "extract_task_text",
    "extract_text_candidates",
    "format_jev_handoff_prompt",
    "goal_names_destructive",
    "inject_pseudo_options",
    "jev_choose_tool_enabled",
    "jev_fast_loop_enabled",
    "load_jev_config",
    "normalize_agent_options",
    "parse_system_one_decision",
    "plan_execution",
    "prune_candidates_for_choice",
    "record_jev_decision",
    "record_jev_session_summary",
    "resolve_safe_scroll_point",
    "run_jev_choose",
    "run_jev_choose_tool",
    "run_jev_fast_loop",
    "run_shadow_evaluation",
    "scrub_for_logs",
    "shadow_evaluation_enabled",
    "typesafe_sdk_available",
    "validate_grounded_action",
    "wait_for_revision_change",
]
